name: test, deploy and run
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # pack zip and read manifest, can be reused in the following steps
      - name: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'extension'
          zipFilePath: 'build/extension.zip'

      - name: create crx extension
        uses: cardinalby/webext-buildtools-chrome-crx-action@6ffc20d012116ea3fa0c6697382b026fc7df9535
        with:
          # zip file made at the packExtensionDir step
          zipFilePath: 'build/extension.zip'
          crxFilePath: 'build/gamestopFirst.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/gamestopFirst.crx

